# Reference & Other Good Stuff {#Ref1}

## Abbreviations

### Rasch Models
> Rasch Models

| Abbreviation | Description | 
| :---        |    :----    | 
| RSM | Rating Scale Model | 
| PCM |Partial Credit Model | 
| MFRM | Many-facet Rasch Model | 
| GLMM | Generalized Linear Mixed Models |

> Diagnostic and Exploratory Rasch Figures

| Abbreviation | Description | 
| :---        |    :----    | 
| ICC | Item Characteristic Curve | 
| IIC | Item Information Function | 
| IRF | Item Response Function | 
| TCC | Test Characteristic Curve | 

> Estimation methods and Estimates

| Abbreviation | Description | 
| :---        |    :----    | 
| AML(E) | Anchored Maximum Likelihood (Estimation)|
| CML(E) | Conditional Maximum Likelihood (Estimation) | 
| EAP | Expected A Posterior (Estimate) | 
| JML(E) | Joint Maximum Likelihood (Estimation) | 
| UCON(E) | Unconditional Maximum Likelihood (Estimation) | 
| MML(E) | Marginal Maximum Likelihood (Estimation) |
| WLE | Weighted Likelihood Estimate | 

**Note***: JMLE "Joint Maximum Likelihood Estimation" is also called UCON, "Unconditional maximum likelihood estimation". It was devised by [Wright & Panchapakesan](https://www.rasch.org/memo46.htm).

### Useful Rasch Software & R-Packages


## Rasch friendly Jounrals 


## Rasch Model Application Tempaltes


## Reference for this book
