--- 
title: "Companion to BER 670: Rasch Techniques for Constructing and Evaluating Measurement Instruments"
author: "Cheng Hua & Dr. Stefanie Wind"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This is the Rasch R book."
---

# Introduction

This book is still in progress !!! This is a draft. Several sections are still incomplete or unedited.

This book is written to help students enrolled in the University of Alabama, *Rasch Measurement Theory* (BER 670) course led by Professor **Stefanie Wind**.

We hope that the book will be a useful resource to help you learn both R and statistics. If you have any suggestions for improvements, please get in touch with your lovely TA: *Cheng Hua*, at **chua@crimson.ua.edu** 

## Outline of the Topics

The course schedule proceeds as follows: 

**Part I** includes an introduction to the course, an overview of major historical developments Rasch measurement research, and an introduction to foundational concepts related to Rasch measurement theory.

**Part II** includes an introduction to the dichotomous Rasch model, indicators of model-data fit, and practical applications using specialized software.

**Part III** includes an exploration of Rasch models for polytomous data, including the Rating Scale and Partial Credit models, along with practical applications using specialized software.

**Part IV** introduces the Many-Facet Rasch model, and includes practical applications using specialized software.

**Part V** includes an exploration of additional practical considerations related to Rasch measurement, including designs for data collection, differential item and person functioning, and rating scale diagnostics.

**Part VI** is the conclusion of the course in which students have the opportunity to share critiques of articles from their research area and their proposals for constructing a measurement instrument.  

## Student Learning Objectives

Students will: 

•	Describe the motivation for Rasch measurement theory, along with the advantages of this approach for social science measurement

•	Explain and apply concepts related to dichotomous and polytomous Rasch models.

•	Explain and apply concepts related to statistical and graphical indicators of item and person fit.

•	Interpret the results from dichotomous and polytomous Rasch measurement theory analyses.

•	Conduct Rasch measurement theory analyses using specialized computer software.

•	Critically evaluate published research related to social science measurement in general, and Rasch measurement theory in particular.

•	Communicate psychometric principles, measurement results, and interpretations of results through writing and oral presentation.

## Office Hours and Contact Information

- *Instructor:* Stefanie A. Wind, Ph.D.

- *Email:* swind@ua.edu

- *Office:* Carmichael 315

- *Office Hours:* Monday 1:00 pm to 3:00 pm

## Required Textbook
[Bond, T. G., & Fox, C. M. (2015). Applying the Rasch model: Fundamental measurement in the human sciences (3rd ed.). New York, NY: Routledge.](https://stdbooks.com/product/applying-the-rasch-model/?gclid=CjwKCAjwsan5BRAOEiwALzomX1cL2WwCUoLU01YnsW2pQMH2W0QzbHnx6I8DtsxmTez3luPnWFLy5RoC-nUQAvD_BwE)

## Recommended Textbook

[Wilson, M. (2005). Constructing measures: An item response modeling approach. New York, NY: Taylor & Francis.](https://books.google.com/books/about/Constructing_Measures.html?id=yC0DN2ncFEIC)

## Note about readings {-}

In order to ensure the most efficient learning experience, students are encouraged to complete readings before coming to class. Additional readings that are not included in the textbook will be made available on the BlackBoard site.



